name: Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Setting up the job"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Check CodeQL version
        run: /opt/hostedtoolcache/CodeQL/2.19.1/x64/codeql/codeql version --format=json

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Analyze code with CodeQL
        uses: github/codeql-action/analyze@v2

      - name: Enforce required checks
        if: success()
        run: echo "All checks passed"

      - name: Post Initialize CodeQL
        if: always()
        run: echo "CodeQL initialization completed"

      - name: Post Use Node.js
        if: always()
        run: echo "Node.js setup completed"

      - name: Post Checkout code
        if: always()
        run: echo "Code checkout completed"

      - name: Complete job
        if: always()
        run: echo "Job completed successfully"
