name: Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.1.0"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Analyze code with CodeQL
        uses: github/codeql-action/analyze@v2
        with:
          category: "Security"
          output: results.sarif

      - name: Upload SARIF file
        uses: github/code-scanning/sarif-action@v1
        with:
          sarif_file: results.sarif
          category: "CodeQL"
