name: Dependency Updates

on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Check Dependencies
        uses: dependabot/fetch-metadata@v1
